#!/usr/bin/env node
/**
 * Lab Framework — Build Script
 * ═══════════════════════════════════════════════════════════════════
 * Inlines core.css and core.js into self-contained lab HTML files.
 *
 * Usage:
 *   node lab-framework/build.js labs/day1/lab-01-config.js
 *   node lab-framework/build.js --all
 *   node lab-framework/build.js --check   (dry-run, no writes)
 *
 * Why inline?
 *   Labs must work from file:// URLs (USB delivery, air-gapped training
 *   environments). No CDN or relative path resolution guarantees exist.
 *   Inlining at build time preserves self-containment.
 *
 * What this script does NOT do:
 *   - Minify (labs are dev tools; readable source is a feature)
 *   - Bundle imports (the framework has no external dependencies)
 *   - Hot-reload (edit config + re-run build = fast enough)
 * ═══════════════════════════════════════════════════════════════════
 */

const fs   = require('fs');
const path = require('path');

// ─── Paths ─────────────────────────────────────────────────────────────
const FRAMEWORK_DIR = path.join(__dirname);
const PROJECT_ROOT  = path.join(__dirname, '..');
const CORE_CSS_PATH = path.join(FRAMEWORK_DIR, 'core.css');
const CORE_JS_PATH  = path.join(FRAMEWORK_DIR, 'core.js');

// ─── Entry Point ──────────────────────────────────────────────────────
function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    printUsage();
    process.exit(0);
  }

  const dryRun = args.includes('--check');
  const buildAll = args.includes('--all');

  // Read shared framework files
  const coreCSS = readFrameworkFile(CORE_CSS_PATH, 'core.css');
  const coreJS  = readFrameworkFile(CORE_JS_PATH,  'core.js');

  if (buildAll) {
    buildAllLabs(coreCSS, coreJS, dryRun);
  } else {
    // Build specific config files
    args.filter(a => !a.startsWith('--')).forEach(configPath => {
      buildLab(path.resolve(configPath), coreCSS, coreJS, dryRun);
    });
  }
}

// ─── Build All ────────────────────────────────────────────────────────
function buildAllLabs(coreCSS, coreJS, dryRun) {
  const labDirs = ['labs/day1', 'labs/day2', 'labs/day3'];
  const configFiles = [];

  labDirs.forEach(dir => {
    const absDir = path.join(PROJECT_ROOT, dir);
    if (!fs.existsSync(absDir)) return;
    fs.readdirSync(absDir)
      .filter(f => f.endsWith('-config.js'))
      .forEach(f => configFiles.push(path.join(absDir, f)));
  });

  if (configFiles.length === 0) {
    console.log('⚠️  No *-config.js files found in labs/day{1,2,3}/');
    console.log('   Config files follow the pattern: lab-01-config.js');
    return;
  }

  console.log(`Building ${configFiles.length} lab(s)...\n`);
  configFiles.forEach(f => buildLab(f, coreCSS, coreJS, dryRun));
}

// ─── Build One Lab ────────────────────────────────────────────────────
function buildLab(configPath, coreCSS, coreJS, dryRun) {
  if (!fs.existsSync(configPath)) {
    console.error(`✗ Config not found: ${configPath}`);
    return;
  }

  // Dynamic require of config
  let config;
  try {
    config = require(configPath);
  } catch (e) {
    console.error(`✗ Failed to load config: ${configPath}`);
    console.error('  ' + e.message);
    return;
  }

  // Validate required config fields
  const required = ['labKey', 'labName', 'dayNum', 'labNum', 'sectionCount', 'bodyHTML'];
  const missing = required.filter(k => config[k] === undefined);
  if (missing.length > 0) {
    console.error(`✗ Config missing required fields: ${missing.join(', ')}`);
    console.error(`  File: ${configPath}`);
    return;
  }

  // Generate output path
  const labDir    = path.dirname(configPath);
  const outputFile = path.join(labDir, `lab-${String(config.labNum).padStart(2,'0')}-${config.labSlug || slugify(config.labName)}.html`);

  // Build HTML
  const html = generateHTML(config, coreCSS, coreJS);

  if (dryRun) {
    console.log(`✓ [DRY RUN] Would write: ${path.relative(PROJECT_ROOT, outputFile)} (${html.length} bytes)`);
    return;
  }

  fs.writeFileSync(outputFile, html, 'utf8');
  const lines = html.split('\n').length;
  console.log(`✓ Built: ${path.relative(PROJECT_ROOT, outputFile)} (${lines} lines, ${html.length} bytes)`);
}

// ─── HTML Generator ───────────────────────────────────────────────────
function generateHTML(config, coreCSS, coreJS) {
  const title = `Lab ${String(config.labNum).padStart(2,'0')} · ${config.labName} | Agentic AI Engineering`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHTML(title)}</title>
  <!--
    Generated by lab-framework/build.js
    Lab: ${escapeHTML(config.labKey)} | Day ${config.dayNum} | Lab ${config.labNum}
    Framework: core.css v1.0.0 + core.js v1.0.0
    Build date: ${new Date().toISOString()}
  -->
  <style>
/* ── core.css (inlined by build.js) ────────────────────────────── */
${coreCSS}
/* ── Lab-specific styles ────────────────────────────────────────── */
${config.extraCSS || ''}
  </style>
</head>
<body>

  <!-- Progress bar -->
  <div id="progress-bar"></div>

  <!-- Navigation -->
  <nav>
    <div class="nav-brand">
      <span class="nav-badge">Day ${config.dayNum} · Lab ${String(config.labNum).padStart(2,'0')}</span>
      <span>${escapeHTML(config.labName)}</span>
    </div>
    <div id="nav-dots" class="nav-sections" role="list"></div>
    <div class="nav-stats">
      <div class="xp-display">⚡ <span id="xp-value">0</span> XP</div>
      ${config.showStreak !== false ? '<div class="streak-display" id="streak-display"></div>' : ''}
      <button class="btn btn-ghost" onclick="LabFramework.exportReflections()" style="padding:6px 14px;font-size:13px;">↓ Export</button>
    </div>
  </nav>

  <!-- Lab content (from config.bodyHTML) -->
${config.bodyHTML || '<!-- bodyHTML not provided in config -->'}

  <!-- Attribution footer -->
  <footer class="lab-footer">
    <p>
      &ldquo;Claude&rdquo; and &ldquo;Claude Code&rdquo; are trademarks of Anthropic, PBC.
      This course is not affiliated with or endorsed by Anthropic.
      All product names, logos, and trademarks are the property of their respective owners
      and are referenced here for educational purposes only.
    </p>
    <p>
      Fonts: <a href="https://fonts.google.com/specimen/Inter" rel="noopener">Inter</a>
      and <a href="https://fonts.google.com/specimen/JetBrains+Mono" rel="noopener">JetBrains Mono</a>
      via Google Fonts under the
      <a href="https://scripts.sil.org/OFL" rel="noopener">SIL Open Font License 1.1</a>.
    </p>
    <p>Course content &copy; 2026 Agentic AI Engineering Course. Educational use.</p>
  </footer>

  <!-- core.js (inlined by build.js) -->
  <script>
/* ── core.js (inlined by build.js) ────────────────────────────── */
${coreJS}
  </script>

  <!-- Lab initializer (from config) -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      LabFramework.init(${JSON.stringify({
        labKey:       config.labKey,
        labName:      config.labName,
        dayNum:       config.dayNum,
        labNum:       config.labNum,
        sectionCount: config.sectionCount,
        showStreak:   config.showStreak !== false,
        concepts:     config.concepts || {}
      }, null, 6)});

      ${config.onInit || '// No lab-specific init'}
    });
  </script>

  <!-- Lab-specific scripts (from config.extraJS) -->
  ${config.extraJS ? `<script>\n${config.extraJS}\n  </script>` : '<!-- No lab-specific JS -->'}

</body>
</html>`;
}

// ─── Helpers ──────────────────────────────────────────────────────────
function readFrameworkFile(filePath, name) {
  if (!fs.existsSync(filePath)) {
    console.error(`✗ Framework file not found: ${filePath}`);
    console.error(`  Run this script from the project root.`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  console.log(`✓ Loaded ${name} (${content.length} bytes)`);
  return content;
}

function escapeHTML(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function slugify(str) {
  return String(str)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function printUsage() {
  console.log(`
Lab Framework Build Script
──────────────────────────
Usage:
  node lab-framework/build.js <config.js>     Build one lab
  node lab-framework/build.js --all            Build all labs
  node lab-framework/build.js --check          Dry run (no writes)
  node lab-framework/build.js --help           Show this help

Config file format (lab-01-config.js):
  module.exports = {
    labKey:       'lab-01',
    labName:      'The Paradigm Shift',
    labSlug:      'paradigm-shift',
    dayNum:       1,
    labNum:       1,
    sectionCount: 6,
    concepts:     { /* CONCEPT_REGISTRY entries */ },
    extraCSS:     '/* lab-specific CSS */',
    extraJS:      '// lab-specific JS',
    onInit:       '// code to run after LabFramework.init()',
    bodyHTML:     '<!-- lab section HTML -->',
  };

Examples:
  node lab-framework/build.js labs/day1/lab-01-config.js
  node lab-framework/build.js --all --check
`);
}

// ─── Run ───────────────────────────────────────────────────────────────
main();
